try{
    console.log("hello")
    console.log(a)
} catch (err){
    console.log("handled", err)
} finally {
    console.log("finally")
}

console.log("end")